const TALLYSUCCESS = "tally success";
const MOREPENDINGTHANCONFIRMED = "more pending than confirmed";
const NOCONFIRMED = "no confirmed";
const RECEIPTEMAIL = "RECEIPT";
const OTHERCHANNELEMAIL = "OTHERCHANNEL";
const MANUALREQEMAIL = "MANUALREQ";

module.exports = {
  TALLYSUCCESS,
  MOREPENDINGTHANCONFIRMED,
  NOCONFIRMED,
  RECEIPTEMAIL,
  OTHERCHANNELEMAIL,
  MANUALREQEMAIL,
};
